
title: KM Portfolio
email: katherine.molloy@gmail.com
description: Portfolio site May 2019
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://myportfolio.github.io"
github_username:  rjpanda

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  - mywork

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
