
title: KM Portfolio
email: katherine.molloy@gmail.com
description: Portfolio site May 2019
baseurl: /myportfolio
url: "https://myportfolio.github.io"
github_username:  rjpanda

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections:
  - mywork
output: true

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
