
title: KM Portfolio
email: katherine.molloy@gmail.com
description: Portfolio site May 2019
baseurl: "/myportfolio"
url: "http://myportfolio.github.io"
github_username:  rjpanda


# Build settings
markdown: kramdown
input: GFM
parse_block_html: true
auto_ids: true
hard_wrap: false
syntax_highlighter: rouge

theme: minima
plugins:
  - jekyll-feed

collections:
  mywork:
  output: true
permalink: pretty

defaults:
scope:
path: _mywork
Values:
layout: project-template

excerpt_separator: ""
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
